### ISSUE TITLE
The SRPM is not buildable

### ISSUE THREAD

**Issue by voxik** [xsuchy/create-fake-rpm#4] opened 2020-11-07 17:57 UTC
~~~
$ create-fake-rpm jre-for-flexibee-rhbz1882240 jre=1.8.0 
Wrote: /home/vondruch/fafa/fake-jre-for-flexibee-rhbz1882240-0-0.src.rpm

$ mock -r fedora-rawhide-x86_64  fake-jre-for-flexibee-rhbz1882240-0-0.src.rpm 

... snip ...

Start: build setup for fake-jre-for-flexibee-rhbz1882240-0-0.src.rpm
warning: line 3: Possible unexpanded macro in: Name: fake-%{fake_name}
warning: line 5: Possible unexpanded macro in: Version: %{fake_version}
warning: line 6: Possible unexpanded macro in: Release: %{fake_release}
error: line 11: Dependency tokens must begin with alpha-numeric, '_' or '/': Provides: %{fake_provides}

... snip ...
~~~

**Comment by xsuchy** [comment] 2020-11-07 21:40
I believe this was fixed in commit d4f77ad

**Comment by voxik** [comment] 2020-11-08 16:59
I don't think so. Firstly, the d4f77ad references just `%{fake_provides}`, secondly. The macros are obviously not expanded in the resulting SRPM, which should be the case. Otherwise, the RPM build would need to run with the same macros. IOW, defining the macros to build the SRPM has mostly no influence on anything.

**Comment by xsuchy** [comment] 2020-11-08 17:35
The reproducer works for me with the current master. Can you try it again with https://bodhi.fedoraproject.org/updates/FEDORA-2020-31c5798d71

**Comment by voxik** [comment] 2020-11-08 21:10
I fails with the same error. But really, how it could work?

~~~
$ rpm -q create-fake-rpm 
create-fake-rpm-4-1.fc34.noarch

$ create-fake-rpm jre-for-flexibee-rhbz1882240 jre=1.8.0
Wrote: /home/vondruch/fakefake/fake-jre-for-flexibee-rhbz1882240-0-0.src.rpm

$ rpm2cpio fake-jre-for-flexibee-rhbz1882240-0-0.src.rpm | cpio -ivd
template.spec
2 blocks

$ cat template.spec 
# Do not change this!
# For the sake of all people working on a support.
Name: fake-%{fake_name}

Version: %{fake_version}
Release: %{fake_release}
License: CC0

Summary: Faked provides of %{fake_provides}

Provides: %{fake_provides}
Provides: %{fake_name}
BuildArch: noarch

%description
This package is empty. It has been created to put fake entry in rpmdb.

%files
#intentionaly empty

%changelog
#intentionaly empty
~~~

I'd need to run `mock` with the required variables defined.

**Comment by voxik** [comment] 2020-11-08 21:11
Or maybe I just don't understand the intended workflow. What would be the reason for providing the SRPM by default, if I can't use it later to build the resulting RPM without additional hassle.

**Comment by xsuchy** [comment] 2020-11-08 23:03
Ah, got it. You have to use `--build` param.  But maybe I can create SRPM which is self-contained.

**Closed as completed** 2020-12-26 17:28 UTC
